# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  startupProject: 'StoreApp.Web'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(startupProject)/bin/$(buildConfiguration)/**/publish/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(7b0f809c-844b-477f-b985-811ff1bab8fe)'
    appType: 'webApp'
    WebAppName: 'bewell-storeapp-revature'
    packageForLinux: '$(System.DefaultWorkingDirectory)/$(startupProject)/bin/$(buildConfiguration)/**/publish/*.zip'